CREATE DATABASE IF NOT EXISTS
form_db;
USE form_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  phone_number INT(15) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  Reason NVARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);